stages:
  - build

build:
  stage: build
  image: registry.ekuaibao.com/ci/ci-nodejs:12.11.1
  script:
    - npm install --registry=https://npm.ekuaibao.com
    - npm run publish2npm
  only:
    - /^v?\d+(\.\d+)+[\.\-_\w]*/
  tags:
    - i9
